@startuml componentDiagram

interface "Search" as search
interface "Payment" as payment
interface "Booking" as booking
interface "Cancellation" as cancel
interface "Print" as print

[Customer Portal] as portal
[Ticket Management] as ticketMgmt
[Payment Gateway] as paymentGw
[Booking System] as bookingSys
[Reservation Database] as db
[Courier Service] as courier
[Print Service] as printer

portal -right-> search
portal -down-> booking
portal -down-> cancel

ticketMgmt -up-( search
ticketMgmt -up-( booking
ticketMgmt -up-( cancel
ticketMgmt -- db

bookingSys -left-( booking
bookingSys -- db
bookingSys -right-> payment

paymentGw -left-( payment
paymentGw -- db

courier -- ticketMgmt : i-ticket
printer -- ticketMgmt : e-ticket

@enduml